name: "build"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          # Make sure to set a version number!
          version: 1.38.40
          # This is the name of the cache folder.
          # The cache folder will be placed in the build directory,
          #  so make sure it doesn't conflict with anything!
          actions-cache-folder: 'emsdk-cache'
      - uses: mymindstorm/setup-emsdk@v11
      - name: Verify
        run: emcc -v
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Build

        run: emcc main.cpp
